//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Agent_WebApp_JoseRodriguez.CurrencyExchangeRate_ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CurrencyExchangeRate_ServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExchangeRateCalculator", ReplyAction="http://tempuri.org/IService1/ExchangeRateCalculatorResponse")]
        double ExchangeRateCalculator(string currencyFrom, string currencyTo, System.DateTime dateOfConvertion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExchangeRateCalculator", ReplyAction="http://tempuri.org/IService1/ExchangeRateCalculatorResponse")]
        System.Threading.Tasks.Task<double> ExchangeRateCalculatorAsync(string currencyFrom, string currencyTo, System.DateTime dateOfConvertion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Travel_Agent_WebApp_JoseRodriguez.CurrencyExchangeRate_ServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Travel_Agent_WebApp_JoseRodriguez.CurrencyExchangeRate_ServiceReference.IService1>, Travel_Agent_WebApp_JoseRodriguez.CurrencyExchangeRate_ServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double ExchangeRateCalculator(string currencyFrom, string currencyTo, System.DateTime dateOfConvertion) {
            return base.Channel.ExchangeRateCalculator(currencyFrom, currencyTo, dateOfConvertion);
        }
        
        public System.Threading.Tasks.Task<double> ExchangeRateCalculatorAsync(string currencyFrom, string currencyTo, System.DateTime dateOfConvertion) {
            return base.Channel.ExchangeRateCalculatorAsync(currencyFrom, currencyTo, dateOfConvertion);
        }
    }
}
